# Generated by Django 2.2 on 2019-04-04 20:43

from django.db import migrations

def seed(apps, schema_editor):
    Product = apps.get_model('mango', 'Product')
    Cart = apps.get_model('mango', 'Cart')
    buy_cart = Cart(name="Buy now")
    buy_cart.save()

    Product(cart=buy_cart, name='Good Boy Treats', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In vitae turpis massa sed. Ornare arcu odio ut sem.',
        product_image='https://t3.ftcdn.net/jpg/01/14/47/90/240_F_114479019_b3vCm8nqxUUDVFp7FfHasa1OP9csVtuw.jpg',price=13).save()
    Product(cart=buy_cart, name='Assorted Kibbles', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/01/79/42/77/240_F_179427778_LGZUy5Lw3lFiOF0iEx70EgHbdOU6Wf3h.jpg',price=37).save()
    Product(cart=buy_cart, name='Slabs! Pure Meat', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/02/23/86/61/240_F_223866102_det3tI7C8j7ajvwq4jXqqdR6EtgZwyCP.jpg',price=9).save()
    Product(cart=buy_cart, name='Feather Wand', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/02/34/32/75/240_F_234327502_3nB3V4jmOn6rnsTaBgNPF8MPcsV5XrFQ.jpg',price=4).save()
    Product(cart=buy_cart, name='Meow Meow Box', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/02/09/31/25/240_F_209312535_EVe5FnRPnoLMywawEs0RkJ5ssYCN51L9.jpg',price=25).save()
    Product(cart=buy_cart, name='Multi-Colored Ball', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/00/85/31/53/240_F_85315358_bJP5PppocQrwWbtZ1gkBIXFffjfGdoc5.jpg',price=7).save()
    Product(cart=buy_cart, name='Meatless Squeaker', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t3.ftcdn.net/jpg/01/25/84/60/240_F_125846036_1LMeqbW52zOUYBkZlUksp3RDd4eAjqwb.jpg',price=5).save()
    Product(cart=buy_cart, name='Macaw Totem', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t3.ftcdn.net/jpg/00/87/62/88/240_F_87628861_hgtMUAo2RtqOQvyGjMhlsiCOKZjJaSY8.jpg',price=14).save()
    Product(cart=buy_cart, name='Doggie Feasts', description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet.',
        product_image='https://t4.ftcdn.net/jpg/00/83/14/83/240_F_83148379_zdhNNFODRqYjkgxf21PqizSOkRDopjre.jpg',price=76).save()
 

def fallow(apps, schema_editor):
    Product = apps.get_model('mango', 'Product')
    Cart = apps.get_model('mango', 'Cart')
    Cart.objects.all().delete()
    Product.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
